services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-builder
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev:frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-builder
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    command: npm run dev:backend